[build]
  publish = "_site"
  command = "yarn build"
  functions = "functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "yarn dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"


