[build]
  publish = "_site"
  command = "yarn build"
  functions = "functions"
  # sync with .tool-versions
  NODE_VERSION = "16.15.1"

[dev]
  command = "yarn dev"

[[redirects]]
  from = "/api/ga/*"
  to = "/.netlify/functions/ga"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"


